<?php

return [
    'cities' => [
        // المنطقة الوسطى
        ['name' => 'الرياض', 'name_en' => 'riyadh'],
        ['name' => 'الخرج', 'name_en' => 'al-kharj'],
        ['name' => 'المجمعة', 'name_en' => 'al-majmaah'],
        ['name' => 'المزاحمية', 'name_en' => 'al-muzahimiyah'],
        ['name' => 'وادي الدواسر', 'name_en' => 'wadi-aldawasir'],
        ['name' => 'الدوادمي', 'name_en' => 'ad-dawadimi'],
        ['name' => 'عفيف', 'name_en' => 'afif'],
        ['name' => 'القويعية', 'name_en' => 'al-quwayiyah'],
        ['name' => 'حوطة بني تميم', 'name_en' => 'hawtat-bani-tamim'],
        ['name' => 'الأفلاج', 'name_en' => 'al-aflaj'],
        ['name' => 'السليل', 'name_en' => 'as-sulayyil'],
        ['name' => 'ضرما', 'name_en' => 'diriyah'],
        ['name' => 'شقراء', 'name_en' => 'shaqra'],
        ['name' => 'رماح', 'name_en' => 'rumah'],
        ['name' => 'ثادق', 'name_en' => 'thadiq'],
        ['name' => 'حريملاء', 'name_en' => 'huraymila'],

        // المنطقة الغربية
        ['name' => 'جدة', 'name_en' => 'jeddah'],
        ['name' => 'مكة المكرمة', 'name_en' => 'makkah'],
        ['name' => 'المدينة المنورة', 'name_en' => 'madinah'],
        ['name' => 'الطائف', 'name_en' => 'taif'],
        ['name' => 'ينبع', 'name_en' => 'yanbu'],
        ['name' => 'رابغ', 'name_en' => 'rabigh'],
        ['name' => 'الليث', 'name_en' => 'allith'],
        ['name' => 'القنفذة', 'name_en' => 'alqunfudhah'],
        ['name' => 'عسفان', 'name_en' => 'usfan'],
        ['name' => 'أملج', 'name_en' => 'umluj'],
        ['name' => 'الوجه', 'name_en' => 'al-wajh'],
        ['name' => 'ضباء', 'name_en' => 'duba'],
        ['name' => 'تيماء', 'name_en' => 'tayma'],
        ['name' => 'خيبر', 'name_en' => 'khaybar'],
        ['name' => 'العلا', 'name_en' => 'al-ula'],
        ['name' => 'بدر', 'name_en' => 'badr'],
        ['name' => 'المهد', 'name_en' => 'al-mahd'],
        ['name' => 'الحناكية', 'name_en' => 'al-hanakiyah'],

        // المنطقة الشرقية
        ['name' => 'الدمام', 'name_en' => 'dammam'],
        ['name' => 'الخبر', 'name_en' => 'al-khobar'],
        ['name' => 'الظهران', 'name_en' => 'dhahran'],
        ['name' => 'الأحساء', 'name_en' => 'al-ahsa'],
        ['name' => 'الجبيل', 'name_en' => 'jubail'],
        ['name' => 'القطيف', 'name_en' => 'alqatif'],
        ['name' => 'حفر الباطن', 'name_en' => 'hafar-albatin'],
        ['name' => 'سيهات', 'name_en' => 'saihat'],
        ['name' => 'الخفجي', 'name_en' => 'alkhafji'],
        ['name' => 'الصفوى', 'name_en' => 'safwa'],
        ['name' => 'راس تنورة', 'name_en' => 'ras-tanura'],
        ['name' => 'بقيق', 'name_en' => 'buqayq'],
        ['name' => 'النعيرية', 'name_en' => 'an-nuayriyah'],
        ['name' => 'تاروت', 'name_en' => 'tarout'],
        ['name' => 'العديد', 'name_en' => 'al-udeid'],
        ['name' => 'قرية العليا', 'name_en' => 'qaryat-al-ulya'],

        // المنطقة الشمالية
        ['name' => 'تبوك', 'name_en' => 'tabuk'],
        ['name' => 'حائل', 'name_en' => 'hail'],
        ['name' => 'عرعر', 'name_en' => 'arar'],
        ['name' => 'سكاكا', 'name_en' => 'sakaka'],
        ['name' => 'الجوف', 'name_en' => 'aljawf'],
        ['name' => 'طريف', 'name_en' => 'turaif'],
        ['name' => 'طبرجل', 'name_en' => 'tubarjal'],
        ['name' => 'القريات', 'name_en' => 'al-qurayyat'],
        ['name' => 'رفحاء', 'name_en' => 'rafha'],
        ['name' => 'العيساوية', 'name_en' => 'al-isawiyah'],
        ['name' => 'الشنان', 'name_en' => 'ash-shinan'],
        ['name' => 'بقعاء', 'name_en' => 'baqaa'],
        ['name' => 'الغزالة', 'name_en' => 'al-ghazalah'],
        ['name' => 'موقق', 'name_en' => 'muwayqiq'],
        ['name' => 'الشملي', 'name_en' => 'ash-shamli'],

        // المنطقة الجنوبية
        ['name' => 'أبها', 'name_en' => 'abha'],
        ['name' => 'خميس مشيط', 'name_en' => 'khamis-mushait'],
        ['name' => 'جازان', 'name_en' => 'jazan'],
        ['name' => 'نجران', 'name_en' => 'najran'],
        ['name' => 'بيشة', 'name_en' => 'bisha'],
        ['name' => 'الباحة', 'name_en' => 'al-bahah'],
        ['name' => 'بلجرشي', 'name_en' => 'baljurashi'],
        ['name' => 'محايل عسير', 'name_en' => 'muhayil-asir'],
        ['name' => 'النماص', 'name_en' => 'alnamas'],
        ['name' => 'صبيا', 'name_en' => 'sabya'],
        ['name' => 'أبو عريش', 'name_en' => 'abu-arish'],
        ['name' => 'صامطة', 'name_en' => 'samtah'],
        ['name' => 'الدرب', 'name_en' => 'ad-darb'],
        ['name' => 'فرسان', 'name_en' => 'farasan'],
        ['name' => 'الحرث', 'name_en' => 'al-harth'],
        ['name' => 'ضمد', 'name_en' => 'damad'],
        ['name' => 'بيش', 'name_en' => 'baysh'],
        ['name' => 'العارضة', 'name_en' => 'al-aridah'],
        ['name' => 'أحد رفيدة', 'name_en' => 'ahad-rufaidah'],
        ['name' => 'ظهران الجنوب', 'name_en' => 'dhahran-al-janub'],
        ['name' => 'سراة عبيدة', 'name_en' => 'sarat-abidah'],
        ['name' => 'رجال ألمع', 'name_en' => 'rijal-almaa'],
        ['name' => 'تنومة', 'name_en' => 'tanomah'],
        ['name' => 'بارق', 'name_en' => 'bariq'],
        ['name' => 'المندق', 'name_en' => 'al-mandaq'],
        ['name' => 'قلوة', 'name_en' => 'qilwah'],
        ['name' => 'العقيق', 'name_en' => 'al-aqiq'],
        ['name' => 'المخواة', 'name_en' => 'al-mikhwah'],
        ['name' => 'غامد الزناد', 'name_en' => 'ghamid-al-zinad'],
        ['name' => 'شرورة', 'name_en' => 'sharurah'],
        ['name' => 'حبونا', 'name_en' => 'habuna'],
        ['name' => 'ثار', 'name_en' => 'thar'],
        ['name' => 'يدمة', 'name_en' => 'yadamah'],
        ['name' => 'خباش', 'name_en' => 'khabbash'],

        // مدن أخرى مهمة
        ['name' => 'القصيم', 'name_en' => 'al-qassim'],
        ['name' => 'بريدة', 'name_en' => 'buraidah'],
        ['name' => 'عنيزة', 'name_en' => 'unaizah'],
        ['name' => 'الرس', 'name_en' => 'ar-rass'],
        ['name' => 'المذنب', 'name_en' => 'al-mithnab'],
        ['name' => 'البكيرية', 'name_en' => 'al-bukairiyah'],
        ['name' => 'البدائع', 'name_en' => 'al-badai'],
        ['name' => 'رياض الخبراء', 'name_en' => 'riyadh-al-khabra'],
        ['name' => 'عيون الجواء', 'name_en' => 'uyun-al-jiwa'],
        ['name' => 'الأسياح', 'name_en' => 'al-asyah'],
        ['name' => 'النبهانية', 'name_en' => 'an-nabhaniyah'],
        ['name' => 'ضرية', 'name_en' => 'dariyah'],
        ['name' => 'عقلة الصقور', 'name_en' => 'uqlat-as-suqur'],
    ]
];
